export const projects = [
  {
    id: 1,
    title: "فيلا كراون الفاخرة",
    location: "التجمع الخامس، القاهرة الجديدة",
    category: "فيلات",
    description: "فيلا مستقلة بتصميم عصري فائق الفخامة، تتميز بمسبح خاص وحديقة واسعة مع إطلالة بانورامية لا تُنسى. تشطيبات الترا سوبر لوكس مع تقنيات المنزل الذكي بالكامل.",
    price: "25,000,000 ج.م",
    stats: { beds: 5, baths: 6, area: "850 م²" },
    images: ["/projects/project-1.png", "/projects/project-2.png", "/projects/project-3.png", "/projects/project-4.png"],
    featured: true, 
    amenities: ["مسبح خاص", "حديقة واسعة", "جراج مخصص", "نظام سمارت هوم", "تكييف مركزي"],
    finishing: "ألترا سوبر لوكس",
    payment: "كاش أو تقسيط على 5 سنوات",
    floor_plans: [{ title: "الدور الأرضي", image: "/projects/project-5.png", description: "يحتوي على ريسبشن كبير، مطبخ مفتوح، وحمام ضيوف." }]
  },
  {
    id: 2,
    title: "بنتهاوس سكاي لاين",
    location: "الشيخ زايد",
    category: "شقق",
    description: "بنتهاوس فاخر في أعلى نقطة بالمدينة، تشطيبات ألترا سوبر لوكس مع تراس ضخم وحمام سباحة علوي. الخصوصية المطلقة مع إطلالة بانورامية خلابة على المساحات الخضراء.",
    price: "12,500,000 ج.م",
    stats: { beds: 3, baths: 3, area: "320 م²" },
    images: ["/projects/project-4.png", "/projects/project-5.png", "/projects/project-6.png"],
    featured: false,
    amenities: ["تراس ضخم", "حمام سباحة علوي", "نظام أمان 24/7", "جراج تحت الأرض", "جاكوزي"],
    finishing: "ألترا سوبر لوكس",
    payment: "تقسيط على 7 سنوات",
    floor_plans: []
  },
  {
    id: 3,
    title: "مقر إداري برستيج",
    location: "العاصمة الإدارية الجديدة",
    category: "تجاري",
    description: "مساحة مكتبية ذكية في قلب حي المال والأعمال، مجهزة بأحدث التقنيات وبنية تحتية متطورة للشركات الكبرى. واجهات زجاجية مزدوجة مع أنظمة توفير الطاقة.",
    price: "8,000,000 ج.م",
    stats: { beds: 0, baths: 2, area: "150 م²" },
    images: ["/projects/project-7.png", "/projects/project-8.png", "/projects/project-9.png"],
    featured: false,
    amenities: ["واجهات زجاجية", "أنظمة توفير الطاقة", "مصاعد سريعة", "إنترنت فائق السرعة", "غرف اجتماعات ذكية"],
    finishing: "نصف تشطيب",
    payment: "تقسيط على 10 سنوات",
    floor_plans: []
  },
  {
    id: 4,
    title: "تاون هاوس الزمرد",
    location: "المستقبل سيتي",
    category: "فيلات",
    description: "تاون هاوس بتصميم مودرن وسط مساحات خضراء شاسعة، مثالي للعائلات التي تبحث عن الهدوء والرقي. يضم حديقة أمامية وخلفية وتراس علوي كبير.",
    price: "15,000,000 ج.م",
    stats: { beds: 4, baths: 4, area: "400 م²" },
    images: ["/projects/project-10.png", "/projects/project-11.png", "/projects/project-12.png"],
    featured: false,
    amenities: ["حديقة خاصة", "تراس علوي", "نادي صحي مشترك", "منطقة لعب للأطفال"],
    finishing: "تشطيب كامل",
    payment: "تقسيط على 8 سنوات",
    floor_plans: []
  },
  {
    id: 5,
    title: "شاليه لاجونا المائي",
    location: "الساحل الشمالي",
    category: "شاليهات",
    description: "شاليه صف أول على اللاجونا الكريستالية، يجمع بين الفخامة والهدوء في واحدة من أرقى قرى الساحل الشمالي. تصميم استثنائي يسمح بدخول ضوء الشمس الطبيعي.",
    price: "9,500,000 ج.م",
    stats: { beds: 2, baths: 2, area: "120 م²" },
    images: ["/projects/project-13.png", "/projects/project-14.png"],
    featured: true,
    amenities: ["إطلالة مائية", "دخول الشاطئ", "حمامات سباحة مشتركة", "أمن وحراسة"],
    finishing: "تشطيب كامل",
    payment: "تقسيط على 6 سنوات",
    floor_plans: []
  },
  {
    id: 6,
    title: "دوبلكس جاردن",
    location: "أكتوبر بارك",
    category: "شقق",
    description: "شقة دوبلكس بحديقة خاصة ومدخل مستقل، توفر خصوصية تامة وتصميم داخلي يستغل المساحات بعبقرية، مع غرف نوم ماستر واسعة وتشطيبات راقية.",
    price: "11,000,000 ج.م",
    stats: { beds: 4, baths: 3, area: "280 م²" },
    images: ["/projects/project-15.png", "/projects/project-16.png", "/projects/project-17.png"],
    featured: false,
    amenities: ["مدخل مستقل", "حديقة خاصة", "تشطيبات فاخرة", "نادي اجتماعي"],
    finishing: "ألترا سوبر لوكس",
    payment: "كاش",
    floor_plans: []
  },
  {
    id: 7,
    title: "توين هاوس الكرمة",
    location: "التجمع الأول",
    category: "فيلات",
    description: "توين هاوس بتشطيبات كلاسيكية راقية في كمبوند متكامل الخدمات مع نادي اجتماعي ومناطق ترفيهية. واجهات حجرية فخمة ومداخل رخامية.",
    price: "18,000,000 ج.م",
    stats: { beds: 5, baths: 5, area: "500 م²" },
    images: ["/projects/project-18.png", "/projects/project-19.png", "/projects/project-20.png"],
    featured: false,
    amenities: ["واجهات حجرية", "مداخل رخامية", "نادي اجتماعي", "أمن 24 ساعة"],
    finishing: "تشطيب كلاسيكي",
    payment: "تقسيط على 5 سنوات",
    floor_plans: []
  },
  {
    id: 8,
    title: "قصر الأندلس",
    location: "المنصورية",
    category: "فيلات",
    description: "قصر فائق الفخامة بتصميم أندلسي عريق، يمتد على مساحة شاسعة مع حدائق غناء ونوافير مذهلة. تحفة معمارية نادرة لمحبي التميز المطلق والتفرد.",
    price: "75,000,000 ج.م",
    stats: { beds: 8, baths: 10, area: "2500 م²" },
    images: ["/projects/project-8.png", "/projects/project-9.png", "/projects/project-10.png"],
    featured: true,
    amenities: ["حدائق شاسعة", "نوافير مذهلة", "مسبح أوليمبي", "ملحق للخدم", "تصميم أندلسي"],
    finishing: "ألترا سوبر لوكس",
    payment: "كاش",
    floor_plans: []
  }
];
